# Generated by Django 5.2 on 2025-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_supportticket_answer_supportticket_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxworkerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
